
service: blue-green


# provider:
#   name: aws
#   runtime: nodejs6.10
#   timeout: 300

# functions:
#   hello:
#     handler: handler.hello

provider:
  name: aws
  # stage: ${opt:stage}
  runtime: nodejs6.10
  environment:
    CONFIG_S3_BUCKET: "${file(env.yml):${self:provider.stage}.CONFIG_S3_BUCKET}"
  region: eu-west-1
  timeout: 300
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:ListBucket
        - s3:GetObject
      Resource:  
        - "${file(env.yml):${self:provider.stage}.CONFIG_S3_BUCKET}"
        - "${file(env.yml):${self:provider.stage}.CONFIG_S3_BUCKET}/*"
    - Effect: "Allow"
      Action:
        - sqs:SendMessage
      Resource:
        - "${file(env.yml):${self:provider.stage}.DLQ_SQS_TOPIC}"


functions:
  hello:
    handler: handler.hello
    events:
      - sns:
          arn: ${file(env.yml):${self:provider.stage}.EVENTS_SNS_TOPIC}
    deadLetter:
      targetArn: ${file(env.yml):${self:provider.stage}.DLQ_SQS_TOPIC}

plugins:
  - serverless-plugin-lambda-dead-letter

